### ISSUE TITLE
Exercise 12: Suggestion solution does not account for `null` returns

### ISSUE THREAD

**Issue by michael-p** [typescript-exercises/typescript-exercises#31]
According to the readme of the stats package, `getMedianElement`, `getMinElement`, ... may return `null` if the passed-in array is empty. However, the suggested solution declares them as follows
```typescript
type GetElement = <T>(input: T[], comparator: Comparator<T>) => T ;
export const getMedianElement: GetElement;
export const getMinElement: GetElement;
```

I would argue that `type GetElement = <T>(input: T[], comparator: Comparator<T>) => T | null;` would be more correct. Sadly, this is not accepted as a solution.

**Comment by oyvind-ege** [comment]
Same applies to `getAverageValue()`:

` export const getAverageValue: <T>(input: T[], getValue: (item: T) => number) => number | null;`

**Comment by tapayne88** [comment]
This looks fixed in [master](https://github.com/typescript-exercises/typescript-exercises/blob/master/src/exercises/12/declarations/stats/index.solution.d.ts), does it just need deploying?
https://github.com/typescript-exercises/typescript-exercises/blob/aa8c44780a15d38c875e2cee384db8a1f49945ce/src/exercises/12/declarations/stats/index.solution.d.ts#L9
https://github.com/typescript-exercises/typescript-exercises/blob/aa8c44780a15d38c875e2cee384db8a1f49945ce/src/exercises/12/declarations/stats/index.solution.d.ts#L14

**Comment by Kobold** [comment]
Thought the same thing. Glad to see I wasn't off!

**Comment by mdevils** [comment]
Sorry for a delay. This update was now released.
